apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: service-specific
  namespace: default #<namespace>
spec:
  selector:
    matchLabels:
      app: service-name
  mtls:
    mode: STRICT
